package com.prosecshane.quoteapp.domain.model

import java.util.UUID

/**
 * The main data class for the app. Contains all of the information
 * needed to store and display a generated quote.
 *
 * @param id Unique ID for every instance. Generated by UUID.
 * @param created Timestamp of the millis when the quote was created.
 * @param content The string of the quote itself.
 * @param keywords Keywords used to create the quote.
 */
data class Quote(
    val id: String = UUID.randomUUID().toString(),
    val created: Long = System.currentTimeMillis(),
    val content: String,
    val keywords: String,
)
