package com.prosecshane.quoteapp.domain.model

/**
 * The message from AI model. Contains the information about the response.
 *
 * @param content The string of the message. In app's context,
 * contains the quote generated by the AI model.
 */
data class ResponseMessage(
    val content: String,
)
